###
GET http://localhost:4004/odata/v4/catelog/A_SalesContract

###
POST http://localhost:4004/odata/v4/catelog/A_SalesContract
Content-Type: application/json

{
  "SalesContract": "",
  "SalesOrganization": "GSO1",
  "DistributionChannel": "G1",
  "OrganizationDivision": "G1",
  "SalesGroup": "",
  "SalesOffice": "",
  "SalesDistrict": "ZGO-E",
  "SoldToParty": "11",
  "CreationDate": "2021-10-11",
  "CreatedByUser": "GAURAV",
  "LastChangeDate": "2021-10-11",
  "LastChangeDateTime": "2021-11-09T15:04:12.504Z",
  "PurchaseOrderByCustomer": "GAS Contract",
  "CustomerPurchaseOrderType": "",
  "CustomerPurchaseOrderDate": null,
  "SalesContractDate": "2021-12-01",
  "TotalNetAmount": 100000000,
  "TransactionCurrency": "EUR",
  "SDDocumentReason": "",
  "PricingDate": "2021-10-11",
  "IncotermsClassification": "FOB",
  "IncotermsTransferLocation": "FOB",
  "IncotermsLocation1": "FOB",
  "IncotermsLocation2": "",
  "IncotermsVersion": "",
  "CustomerPaymentTerms": "0001",
  "PaymentMethod": "",
  "SalesContractValidityStartDate": "2020-04-01",
  "SalesContractValidityEndDate": "2022-12-31",
  "SalesContractValidityPerdUnit": "",
  "SalesContractValidityPerdCat": "",
  "SalesContractSignedDate": null,
  "NmbrOfSalesContractValdtyPerd": "0",
  "SalesContractFollowUpAction": "",
  "SlsContractFollowUpActionDate": null,
  "ContractManualCompletion": "",
  "ReferenceSDDocument": "",
  "ReferenceSDDocumentCategory": "",
  "OverallSDProcessStatus": "B",
  "TotalCreditCheckStatus": "",
  "OverallSDDocumentRejectionSts": "A",
  "to_Item": [
    {
         "SalesContractItem": "10",
                "HigherLevelItem": "",
                "SalesContractItemCategory": "",
                "SalesContractItemText": "",
                "PurchaseOrderByCustomer": "",
                "Material": "2000000014",
                "MaterialByCustomer": "",
                "PricingDate": null,
                "RequestedQuantity": "20000",
                "RequestedQuantityUnit": "MBT",
                "OutlineAgreementTargetAmount": "0",
                "MaterialGroup": "",
                "MaterialPricingGroup": "",
                "ProductionPlant": "IL68",
                "StorageLocation": "",
                "ShippingPoint": "",
                "IncotermsClassification": "",
                "IncotermsTransferLocation": "",
                "IncotermsLocation1": "",
                "IncotermsLocation2": "",
                "CustomerPaymentTerms": "",
                "SalesDocumentRjcnReason": "",
                "ItemBillingBlockReason": "",
                "WBSElement": "",
                "ProfitCenter": "",
                "ReferenceSDDocument": "",
                "ReferenceSDDocumentItem": "",
                "SalesContractValidityStartDate": null,
                "SalesContractValidityEndDate": null,
                "NmbrOfSalesContractValdtyPerd": "",
                "SalesContractValidityPerdUnit": "",
                "SalesContractValidityPerdCat": "",
                "SalesContractSignedDate": null,
                "SalesContractFollowUpAction": "",
                "SlsContractFollowUpActionDate": null
    }
  ]
}
